backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Mis Productos y Reseñas"
    folder: "blog"
    create: true
    fields:
      - { label: "Título del Producto", name: "title", widget: "string" }
      - { label: "Enlace de Amazon", name: "amazon_link", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Tu Opinión (Psicología y Tech)", name: "body", widget: "markdown" }
